TrajectoryPlannerROS:
    max_vel_x: 0.8
    min_vel_x: 0.1
    max_rotational_vel: 0.2
    min_in_place_rotational_vel: 0.1

    acc_lim_th: 1.0
    acc_lim_x: 0.8
    acc_lim_y: 1.0

    holonomic_robot: false
    meter_scoring: true

    vx_samples: 10
    vtheta_samples: 20

    controller_frequency: 10

    yaw_goal_tolerance: 1.0
    xy_goal_tolerance: 0.3
